# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(492, 253)
        Form.setWhatsThis("")
        self.InitializationButton_AWG = QtWidgets.QPushButton(Form)
        self.InitializationButton_AWG.setGeometry(QtCore.QRect(30, 40, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.InitializationButton_AWG.setFont(font)
        self.InitializationButton_AWG.setCheckable(True)
        self.InitializationButton_AWG.setAutoDefault(False)
        self.InitializationButton_AWG.setDefault(False)
        self.InitializationButton_AWG.setObjectName("InitializationButton_AWG")
        self.InitializationButton_Cam = QtWidgets.QPushButton(Form)
        self.InitializationButton_Cam.setGeometry(QtCore.QRect(240, 40, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.InitializationButton_Cam.setFont(font)
        self.InitializationButton_Cam.setCheckable(True)
        self.InitializationButton_Cam.setAutoDefault(False)
        self.InitializationButton_Cam.setDefault(False)
        self.InitializationButton_Cam.setObjectName("InitializationButton_Cam")
        self.FrequencyDial = QtWidgets.QDial(Form)
        self.FrequencyDial.setGeometry(QtCore.QRect(50, 120, 101, 91))
        self.FrequencyDial.setMaximum(300)
        self.FrequencyDial.setObjectName("FrequencyDial")
        self.test_button = QtWidgets.QPushButton(Form)
        self.test_button.setGeometry(QtCore.QRect(250, 130, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.test_button.setFont(font)
        self.test_button.setCheckable(True)
        self.test_button.setAutoDefault(False)
        self.test_button.setDefault(False)
        self.test_button.setObjectName("test_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.InitializationButton_AWG.setText(_translate("Form", "Initialize AWG"))
        self.InitializationButton_Cam.setText(_translate("Form", "Initialize Camera"))
        self.test_button.setText(_translate("Form", "Initialize Camera"))
